### ISSUE TITLE
App crash after switching account

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-legacy#1005]
### Steps to reproduce
1. Switch the account in settings
2. Click on "Files"

### Expected behaviour
App does not crash.

### Actual behaviour
App crash

### Server configuration

**ownCloud version:**
10.0.3

### Client
**iOS version:**
11.2.2
**ownCloud app version:**
3.7.2
**Device model:**
iPhone SE, iPad Pro

**Comment by jesmrec** [comment]
The bug is the same than this one, i mean: https://github.com/owncloud/ios/issues/884

It was fixed for the latest versions, for the moment i can not reproduce with iPhoneX v11.2.2

**Comment by michaelstingl** [comment]
iPad Pro 10.5 with iOS 11.2.5 beta release - I can reproduce 100%. Shall I upload crash logs?

**Comment by nasli** [comment]
>iPad Pro 10.5 with iOS 11.2.5 beta release - I can reproduce 100%. Shall I upload crash logs?

@michaelstingl Yes please, and also detail a bit more the kind of accounts you are using, URLS, different servers, if some have available offline in some folders, shares, uploads or downloadas in progress, Thank you!

**Comment by michaelstingl** [comment]
I can reproduce in very basic scenario:

1. Install 3.7.2 app from App Store
2. Add https://demo:demo@demo.owncloud.org (basic auth)
3. Add https://test:test@demo.owncloud.com (basic auth)
4. Go to settings page and switch to 1st account
5. Tab "Files" button and it immediately crashes 💥 

- iPhone 7 Plus
- iOS 11.2.5

Here is the crash log:
- [Owncloud iOs Client-2018-01-24-203429.ips.zip](https://github.com/owncloud/ios/files/1661415/Owncloud.iOs.Client-2018-01-24-203429.ips.zip)

**Comment by nasli** [comment]
Thanks for the detailed info. 

Please as workaround, before switch to other account sort list of files with "Newest-Oldest" mode instead "A-Z", this should avoid the crash.
