### ISSUE TITLE
App crash after deleting previewed file from server and device

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-legacy#1022]
### Steps to reproduce
1. Open pdf, jpeg, doc or another file supported by viewer
2. Tap on delete the file 
3. Delete from device and server 
4. Application immediately crashes

### Expected behaviour
You can delete the file from server and device. OC go back to parent folder.

### Actual behaviour
App crashes.

### Client
**iOS version:**
11.2.2
**ownCloud app version:**
3.7.2
**Device model:**
iPhone 5s

#### Device log
[Owncloud iOs Client  08.02.18, 11-01.crash.zip](https://github.com/owncloud/ios/files/1707994/Owncloud.iOs.Client.08.02.18.11-01.crash.zip)

00008953

**Comment by michaelstingl** [comment]
Workaround: Delete file from file list (swipe-right)

**Comment by jesmrec** [comment]
iOS12 beta5 -> still happens
