### ISSUE TITLE
Small size difference in videos automatically uploaded

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-legacy#1040]
1. Enable instant upload for videos
2. Take a video with the camera

Comparing the uploaded video with the one stored in camera roll, we can notice a small differences in the size:

94285782 Mar 19 14:42 Video-2018-03-19-14-40-10_0245.MOV  (Auto uploaded)
94317058 Mar 19 14:40 Video-IMG_0245.MOV (original)

or

15991385 AutoUploaded.MOV
15993581 Original.mov

Differences are about 0,01% of the whole size.

**Comment by michaelstingl** [comment]
I've seen previously that videos get processed/rendered before upload. You see bigger difference with Slow-Mo video. Then "Loading…" and the spinner stays in the foreground for a longer time.

Many things changed in the video. Left is the original Slow-Mo video, right is the uploaded one:

![kaleidoscope](https://user-images.githubusercontent.com/214010/38515142-acdfb4ec-3c33-11e8-9748-bcfaf17df368.png)

(Source: [Media Inspector](http://mediainspector.massanti.com/))

**Comment by michaelstingl** [comment]
| confusing spinner before upload starts (40 sec) | no user feedback during upload | progress only shown on Uploads screen |
| --- | --- | --- |
| ![pasted_image_24_05_18__18_32](https://user-images.githubusercontent.com/214010/40498971-d809e0f0-5f80-11e8-9290-faf21ec49217.png) | ![pasted_image_24_05_18__18_33](https://user-images.githubusercontent.com/214010/40499007-ea8a59ee-5f80-11e8-8ae9-152fd0f54d35.png) | ![pasted_image_24_05_18__18_33](https://user-images.githubusercontent.com/214010/40499022-f72aa65e-5f80-11e8-88e1-0891242c93d9.png) |

**Comment by mneuwert** [comment]
@michaelstingl small clarification regarding slo-mo. Slo-mo videos are stored as normal videos just shot with higher frame-rate. And along with the video there is an adjustment PLIST stored declaring the region of the video to be rendered as slo-mo part. So, when exported slo-mo videos are probably re-rendered at "normal" frame rate.

**Comment by michaelstingl** [comment]
Solution available in next version of new iOS App: https://github.com/owncloud/ios-app/pull/852
