### ISSUE TITLE
No automatic upload

### ISSUE THREAD

**Issue by Adspectus** [owncloud/ios-legacy#1078]
When I take pictures on my iPhone, the pictures are not autmatically uploaded, even though I configured this in the settings.

### Steps to reproduce
1. Take a picture
2. Wait some minutes, nothing will happen
3. Open the App, goto Upload, then the picture will appear (as a list entry) and is beeing  uploaded.

### Expected behaviour
The picture should be uploaded in the background without any interaction

### Actual behaviour
Nothing happens

### Server configuration
**Web server:** Apache 2.4/Debian

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 9.1.8 (stable)

**Storage backend (external storage):** None

### Client
**iOS version:** 11.4.1

**ownCloud app version:** 3.7.5

**Device model:** IPhone 8+

#### Web server error log

No relevant entries.

#### ownCloud log (data/owncloud.log)
I am not sure if this is related at all.
```
Exception: {"Message":"HTTP\/1.1 405 The resource you tried to create already exists","Exception":"Sabre\\DAV\\Exception\\MethodNotAllowed","Code":0,"Trace":"#0 \/srv\/www\/vhosts\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(588): Sabre\\DAV\\Server->createCollection('InstantUpload', Object(Sabre\\DAV\\MkCol))\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/srv\/www\/vhosts\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/srv\/www\/vhosts\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \/srv\/www\/vhosts\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/srv\/www\/vhosts\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(61): Sabre\\DAV\\Server->exec()\n#6 \/srv\/www\/vhosts\/owncloud\/remote.php(164): require_once('\/srv\/www\/vhosts...')\n#7 {main}","File":"\/srv\/www\/vhosts\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1121,"User":"uwe"} 
```

**Comment by jesmrec** [comment]
A significant location change is needed to trigger the uploads. Could you try to disable/enable the location services? just in case, to be sure this was the issue.

**Comment by Adspectus** [comment]
I tried that and it changes nothing. Honestly, this is also not what I expect when I set "Instant Upload" and "Background upload". Actually I tried the following:

I am at home in my WLAN. On a PC, I watched the upload folder on my owncloud server.
1. Took a picture.
2. Waited for about an hour, nothing happend.
3. Took a video.
4. The video gets instantly uploaded.
5. Disabled and reenabled location services.
6. Nothing happened.
7. Started owncloud app and go to Uploads. The video is shown as uploaded, the picture as failed, because access credentials are wrong.

Needless to say that this error message is completely wrong. The video has been uploaded with the same credentials and I also use the app to browse folders with the same credentials.

**Comment by Adspectus** [comment]
The story continues: When I tap the failed picture upload, I had to enter my credentials. After that the error message changed to "not available on this device". What? When I go to the Photo app, I can see the picture side by side with the video I took. Very strange.

**Comment by Adspectus** [comment]
- user/password
- Beware, no
- owncloud account? No, only one.

**Comment by jesmrec** [comment]
could you check the steps in the following reported issue? 

https://github.com/owncloud/android/issues/2237

maybe is the same problem.

**Comment by Adspectus** [comment]
There is no such option on my iPhone. The only ones I have is "instant upload of pictures/videos" and "instant upload in background" (see screenshot):

![photo-2018-09-13-12-58-23_0090](https://user-images.githubusercontent.com/8707493/45486729-6d188d80-b75c-11e8-8296-f2334776d3e8.PNG)

**Comment by jesmrec** [comment]
of course, you are right. This is not in iOS yet. i will research a bit more.

**Comment by CuoreSportivo** [comment]
Same issue here, just as described by Adspectus. Automatic upload is not working in the background, but it does when I open the ownCloud app.
I've also noted that sometimes I get the credentials error, but I haven't verified when this happens.

**Comment by jesmrec** [comment]
not able to reproduce here. i assume that the background switch in `Settings` is enabled, and the location change is done (at least to force the uploads)

**Comment by CuoreSportivo** [comment]
Correct, every option is enabled and the location change (not just enabling/disabling) is made. Location Services is "always" enabled, just like the Background App Refresh and Background Instant Upload option.
The phone was also reset to defaults after the iOS 12 upgrade, so I don't think this is an OS issue.

**Comment by souni** [comment]
This issue still exists on iPhone iOS 13. 

In app permissions 
- read/write to photos enabled
- background update enabled
- mobile data enabled

In the ownCloud-app
- auto upload photos enabled
- auto upload videos enabled

**Comment by michaelstingl** [comment]
@souni this is the repo for the ownCloud legacy iOS app. The legacy app is still available in the app store for users with old ownCloud server versions and users with older iOS version. Only security issues will be fixed. I've seen you already posted in the repo for the new app. (https://github.com/owncloud/ios-app/issues/538)
