### ISSUE TITLE
Opening JPG/PNG images in the iOS app no longer works

### ISSUE THREAD

**Issue by lexo-mfleuti** [owncloud/ios-legacy#1125]
### Steps to reproduce
1. Here's a video that shows the bug: https://screenshare.lexo.ch/Video-2023-01-30-19-08-46_7839.mp4
2. This happens to ANY image on the cloud in all the folders.
3. I enabled the DEBUG mode on the server and these are the log entries - which do not show any error:

### Expected behaviour
Images should open without any issue (worked up until about 2-3 weeks ago). When a folder which contains images is marked as "Available offline" the OC client should download all images and make them available offline. 

### Actual behaviour
Images flicker when loading the the overview screen. When an image is selected it seems to be downloaded, is being displayed for a fraction of a second and then disappears. When a folder is marked as "Available offline" the OC clients starts to download images and then goes absolutely crazy. In the "Status" it tries to endlessly download the images of the folder and after a while of unfinite looping through all the images and trying to download them, the app crashes. After restarting the app tries again to download the offline images and crashes again after a while. The only way to solve the issue is to kill the app, uninstall and reinstall it.

### Server configuration
**Web server:**
apache2/jammy-updates,now 2.4.52-1ubuntu4.2 amd64

**Database:**
mariadb-server-core-10.6/jammy-updates,jammy-security,now 1:10.6.11-0ubuntu0.22.04.1 amd64

**PHP version:**
7.4.33

**ownCloud version:**
10.11.0 (stable)

**Storage backend (external storage):**
Local Storage

### Client
**iOS version:**
16.2

**ownCloud app version:**
ownCloud release version 11.11.1 build 230

**Device model:**
iPhone 13 mini (but also tested on other iPhones)

#### Web server error log
```
my.host.name:443 178.22.109.64 - me [30/Jan/2023:19:20:30 +0100] "PROPFIND /remote.php/dav/files/me/ HTTP/1.1" 207 6529 "-" "Mozilla/5.0 (Linux) mirall/3.0.0.9215- (ownCloud, linuxmint-5.15.0-57-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)"
my.host.name:443 178.22.109.64 - me [30/Jan/2023:19:20:31 +0100] "PROPFIND /remote.php/dav/files/me/01%20-%20Logos/00%20-%20Proposals/ HTTP/1.1" 207 7913 "-" "ownCloudApp/11.11.1 (App/230; iOS/16.2; iPhone)"
my.host.name:443 178.22.109.64 - me [30/Jan/2023:19:20:31 +0100] "GET /remote.php/dav/files/me/01%20-%20Logos/00%20-%20Proposals/Logo%20V3-05.jpg HTTP/1.1" 200 222361 "-" "ownCloudApp/11.11.1 (App/230; iOS/16.2; iPhone)"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"0c2bae56-4832-431d-96c6-abdd8883b571","level":0,"time":"Jan 30 19:20:30","remoteAddr":"178.22.109.64","user":"me","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/me\/","message":"updating token 74490, last check is now 1675096370"}
{"reqId":"3646CC27-4762-443D-90B2-892DA2F232A6","level":0,"time":"Jan 30 19:20:31","remoteAddr":"178.22.109.64","user":"me","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/me\/01%20-%20Logos\/00%20-%20Proposals\/","message":"updating token 74513, last check is now 1675102186"}
{"reqId":"14D2877E-451D-482D-AA75-0C15EB15BE19","level":0,"time":"Jan 30 19:20:31","remoteAddr":"178.22.109.64","user":"me","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"GET","url":"\/remote.php\/dav\/files\/me\/01%20-%20Logos\/00%20-%20Proposals\/Logo%20V3-05.jpg","message":"updating token 74513, last check is now 1675102186"}
```

**Comment by ChrisEdS** [comment]
Hello @lexo-mfleuti, this is the wrong repository, you are looking for https://github.com/owncloud/ios-app

**Comment by lexo-mfleuti** [comment]
Thanks a lot @ChrisEdS. I opened the same case here: https://github.com/owncloud/ios-app/issues/1182
