### ISSUE TITLE
Stream music instead of waiting for it to download

### ISSUE THREAD

**Issue by ZacharyDuBois** [owncloud/ios-legacy#155]
It would be nice if OwnCloud could stream music and video instead of waiting for it to download completely before watching/listening.

(From Issue #152 )

**Comment by rperezb** [comment]
Thanks for your comments, for the moment, this feature does not have an eta.

**Comment by blurredmotion** [comment]
Would it help development if a bounty was added to this feature on bountysource? Having video streaming with a html5 player like videojs would be very very handy...

**Comment by supportreq** [comment]
Hi @nasli I guess the streaming url is being implemented in the android app and the web app using the webdav endpoint.. can we not get this up for ios also?

**Comment by Lusitaniae** [comment]
+1

**Comment by nasli** [comment]
Related video streaming follow the discussion here #787
