### ISSUE TITLE
Waiting for server connection On Iphone when load Images

### ISSUE THREAD

**Issue by mapafeto** [owncloud/ios-legacy#199]
I Buy today the apps just for upload images fast to my computer... but when we try load the images to the cloud this give us the follow error and just stay and retries and retries over and over.
![la foto](https://cloud.githubusercontent.com/assets/8076998/3487466/662f4b9c-047f-11e4-90e5-2d925c8fe27e.PNG)

**Comment by wetsixteen** [comment]
I suddenly have this problem (again?)..
latest stable owncloud with nginx/1.6.2, owncloud from tar.bz in root of webserver / no subfolder
webinterface in safari and mac osx desktop app all work completely fine, iOS app (3.4.8) on os x 9.3 has upload problems...

from nginx debug logs:
`2016/04/05 00:59:25 [debug] 16531#0: *3506 SSL_read: -1
2016/04/05 00:59:25 [debug] 16531#0: *3506 SSL_get_error: 2
2016/04/05 00:59:25 [debug] 16531#0: *3506 event timer: 21, old: 1459810770052, new: 1459810770063
2016/04/05 00:59:25 [debug] 16531#0: *3506 http run request: "/remote.php/webdav/untitled folder/Photo-2016-04-04-22-34-47_5440.JPG?"
2016/04/05 00:59:25 [debug] 16531#0: *3506 http read discarded body
2016/04/05 00:59:25 [debug] 16531#0: *3506 SSL_read: -1
2016/04/05 00:59:25 [debug] 16531#0: *3506 SSL_get_error: 2
2016/04/05 00:59:25 [debug] 16531#0: *3506 event timer: 21, old: 1459810770052, new: 1459810770064`
