### ISSUE TITLE
Preview .ogg files

### ISSUE THREAD

**Issue by JohannesTress** [owncloud/ios-legacy#492]
To be honest I'm a little dissapointed that the owncloud client does not preview any floss file formats. Is there something planned for previewing these kind of files? I think as an open source project it should be  kind of self-evident to support other floss projects, or am I wrong here?
Thanks anyway for the great project!

**Comment by rperezb** [comment]
Thanks for your request.

For the moment, previewing of odf, ogg, it´s on the backlog, not expected ftm.

**Comment by nasli** [comment]
Related odf is duplicated of #107
