### ISSUE TITLE
Favorites Filter View

### ISSUE THREAD

**Issue by MTRichards** [owncloud/ios-legacy#652]
As an ownCloud user, I want a favorites view so that I can quickly find files I want on all platforms - including iOS

Acceptance Criteria:
- A filter or tab is available for the user to quickly view all favorites
- the favorites view is a flat view of all favorite flies
- Favorites can be set on mobile or server, and the favorite tag is synced to mobile, desktop and server
- Favorites are by default synced across platforms

Edited:
API available
https://github.com/owncloud/documentation/issues/2950

**Comment by CorneelDragon** [comment]
Hi, we just got a question from one of our end-users about the possibility to add a 'tab' for favorites. It seems this a relatively small question (in comparison with cross platform consistency). Any change this might be implemented soon in the iOS app?

**Comment by michaelstingl** [comment]
server side API exists for favorites: owncloud/documentation#2950

**Comment by michaelstingl** [comment]
Favorites are available on the Quick Access screen of the new iOS app:
https://doc.owncloud.com/ios-app/ios_quick_access.html
