### ISSUE TITLE
iOS Server Notifications - Accept federated shares

### ISSUE THREAD

**Issue by MTRichards** [owncloud/ios-legacy#656]
As an ownCloud user, I want to see my notifications from the server on my iOS device so that I can respond to federated share requests, and also receive notifications from comment posts and other admin pushed notifications

Acceptance Criteria:
- A separate view like in the web interface
- A bell shows when a new notification is there
- A federated share can be accepted on the mobile app, and then pushes that acceptance to the server
- A read of a notification also informs the server that the notification has been viewed
- Uses the server notification API just like desktop

**Comment by nasli** [comment]
Related on Android: https://github.com/owncloud/android/issues/1676

**Comment by butonic** [comment]
this has been implemented in the new ios app https://github.com/owncloud/ios-app/commit/0bd59445532c123350b50e84cbe4ea5a7bf71094#diff-4e08b7cfb04decb7433b5dfa30ac01c1
