### ISSUE TITLE
Issue when displaying PDF in fullscreen

### ISSUE THREAD

**Issue by Aohzan** [owncloud/ios-legacy#707]
Hi,

When I want to display a multipage PDF file in fullscreen, the first page displays correctly, but when I swipe to the next page, this one is cropped and not at the middle.

Thanks

**Comment by nasli** [comment]
Hi @Mati24, thanks for your feedback,
this is in our backlog to change the behaviour of the tap actions in the pdf preview view to fully support fullscreen mode.
