### ISSUE TITLE
Integrate in Files App

### ISSUE THREAD

**Issue by leafarenuk** [owncloud/ios-legacy#941]
I think it would be interesting to integrate ownCloud in the Files App of iOS11. 

There should be information on the Apple developer pages..

________

Tasks pending:

- [x] Update the provider to support enumeration.
- [x] Show the root folder in files app.
- [x]  Make the file provider visible for other apps through files app.
- [ ] Navigate between folders and files.
- [ ] Provide support for all the current supported file extensions.
- [ ] Proper thumbnails and icons for every file.
- [ ] Open files.
- [ ] Save files.
- [ ] Manage different users, showing in files app only the files available for the current active user.

**Comment by jesmrec** [comment]
Thanks for the suggestion!

**Comment by jlegewie** [comment]
That would be awesome. I am adding references to the API here.

https://developer.apple.com/documentation/fileprovider

https://developer.apple.com/videos/play/wwdc2017/243/

https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/FileProvider.html

https://developer.apple.com/documentation/fileprovider/content_and_change_tracking/defining_your_file_provider_s_content

**Comment by michaelstingl** [comment]
Just watched the [video](https://developer.apple.com/videos/play/wwdc2017/243/) and I haven't found solutions for two of my concerns yet:

- All the apps with new method I tested don't work if they've set a passcode or TouchID
- Multiaccount apps result in bad user experience. There is no indicator which account is active, and there is no way to switch accounts from inside the Files app

**Comment by Kamik423** [comment]
Concerining Multiaccount [FileExplorer](https://www.skyjos.com/fileexplorer/), a app for navigating SMB servers on iOS, has a folder for each server on the top file level of the app.

Also: This issue is very important to me. Please implement soon!

**Comment by nasli** [comment]
Thanks for all the references, this is currently under development here https://github.com/owncloud/ios/issues/905

**Comment by michaelstingl** [comment]
@Kamik423 As a workaround, you could add your ownCloud server as a WebDAV account to [FileExplorer](https://www.skyjos.com/fileexplorer/). This WebDAV account shows up as folder in the iOS 11 Files app… (same with [FileBrowser for Business](https://www.stratospherix.com/products/filebrowserforbusiness/))

**Comment by michaelstingl** [comment]
Here you can test an early build of the new app with integration into iOS Files app: https://testflight.apple.com/join/Oktj0iKv  (open link on iOS device) – We'd love to hear your feedback!

This is the related issue in the repo of the new iOS app;
https://github.com/owncloud/ios-app/issues/11

**Comment by 00SteinsGate00** [comment]
Thank you for that early build, it already shows how great this feature will be. This looks like a seemingness integration into iOS.

It works perfectly on my iPhone but didn't work at all on my iPad, constant refreshing of the file view and unable to download files even from within the OwnCloud App itself. Might be a problem with my server though. I'll try again to night.

So far thank you so much, this is just amazing and takes OwnCloud to a whole new level for me. Even the new OwnCloud app itself is so much better now

**Comment by michaelstingl** [comment]
@00SteinsGate00 Thanks for the feedback! Have you seen my reply (mail)?

**Comment by 00SteinsGate00** [comment]
@michaelstingl no I haven't, I even checked the Spam folder :(

**Comment by michaelstingl** [comment]
@00SteinsGate00 This what I wrote:

> The blinking is annoying. This is a know issue we weren't able to fix before the first public beta.
> 
> I'd like to better understand what's going with the image downloads on your device. Could you send us a recording of your screen and capture a debug level log file in Settings > Logging at the same time?

I started to collect some troubleshooting advice here:
https://github.com/owncloud/ios-app/blob/doc/troubleshooting/doc/TROUBLESHOOTING.md

Please send log and screen recording to `apps<at>owncloud.com`

**Comment by michaelstingl** [comment]
@00SteinsGate00 Wait for the new public beta build this Friday, then provide feedback about the new version…

**Comment by cdamken** [comment]
Legacy, closing
