### ISSUE TITLE
Public shares with more than 64 characters 

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-legacy#981]
![photo-2017-12-18-12-28-39_0009](https://user-images.githubusercontent.com/33026403/34106562-f3bccb54-e3f8-11e7-9fad-8fb241dcbd4e.PNG)

### Steps to reproduce
1. Upload a file with more than 64 characters in the file name 
2. Try to make a public share

### Expected behaviour
The share should be auto-shorten to 64 characters.

### Actual behaviour
Sharing not possible. Have to self-shorten the link.

### Server configuration
**Web server:**
10.0.3
**Database:**
n/a
**PHP version:**
n/a

### Client
**iOS version:**
11.1.2
**ownCloud app version:**
3.7.0_alpha_debug
**Device model:**
iPhone 5s

**Comment by jesmrec** [comment]
what is the behaviour in server side?

**Comment by michaelstingl** [comment]
@jesmrec good point…

![files_-_owncloud](https://user-images.githubusercontent.com/214010/34159509-cee638c0-e4c9-11e7-9851-9bf3fb47e70e.png)
(Version **10.0.4**)

@ChrisEdS Please open the issues in ownCloud/core…

**Comment by ChrisEdS** [comment]
Opened here: https://github.com/owncloud/core/issues/29913

**Comment by jesmrec** [comment]
i think this is an improvement, not a bug. It is not a bad behaviour to warn the user about the limit instead of cutting the name.

**Comment by michaelstingl** [comment]
The link name shown in the screenshot has been **automatically generated**. It's confusing for users if oC proposes a link name that get complains seconds later. Why not propose a working link name in the first place?

**Comment by jesmrec** [comment]
i agree, didn't think in the automatic suggestion for the link name. In this case, the name link has to be truncate to 64 chars.
